// Compiles src/wasm/*.wat to a committed TypeScript module of raw bytes.
//
// The bytes are embedded as a numeric array rather than fetched or
// base64-decoded: AudioWorkletGlobalScope has neither fetch nor atob, and
// the module has to be instantiated synchronously in the processor's
// constructor. Run after editing a .wat: node packages/dsp/scripts/build-wasm.mjs
import wabtFactory from "wabt";
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const wasmDir = path.resolve(here, "../src/wasm");

export async function compileWat(file) {
  const wabt = await wabtFactory();
  const source = readFileSync(path.join(wasmDir, file), "utf8");
  const parsed = wabt.parseWat(file, source);
  parsed.validate();
  const { buffer } = parsed.toBinary({ log: false });
  parsed.destroy();
  return Uint8Array.from(buffer);
}

export function renderModule(bytes) {
  const lines = [];
  for (let i = 0; i < bytes.length; i += 24) lines.push(`  ${Array.from(bytes.slice(i, i + 24)).join(", ")},`);
  return `// GENERATED by packages/dsp/scripts/build-wasm.mjs from eq3.wat — do not edit.
// Regenerate after changing the .wat; test/wasm-eq3.test.ts fails if stale.
export const EQ3_WASM_BYTES = new Uint8Array([
${lines.join("\n")}
]);
`;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const bytes = await compileWat("eq3.wat");
  writeFileSync(path.join(wasmDir, "eq3-wasm.generated.ts"), renderModule(bytes));
  console.log(`eq3.wasm: ${bytes.length} bytes`);
}
